export async function GET({ request }: { request: Request }) {
  // Redirect to the actual pagefind.js file generated by the pagefind CLI
  const url = new URL(request.url);
  const baseUrl = url.origin;

  return new Response(null, {
    status: 302,
    headers: {
      Location: `${baseUrl}/pagefind/pagefind.js`,
    },
  });
}
